export enum ApiTag{
	AUTH='Auth',
	ROLE='Role',
	PERMISSION='Permission',
	USER='User',
	MEDIA='Media',
	SELLER='Seller',
	TERM='Term',
	LOCATION='Location',
	CATEGORY='Category',
	BRAND='Brand',
	ATTRIBUTE='Attribute',
	PRODUCT='Product',
	INVENTORY='Inventory',
	VENDOR='Vendor',
	PURCHASE_ORDER='Purchase Order',
	VOUCHER='Voucher',
	SHOPPING_CART='Shopping Cart',
	ORDER='Order',
	CUSTOMER='Customer',
	SETTINGS='Settings',
	REPORT='Report',
}